/* 
 * SaasPro
 *
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using avalara.comms.rest.v2.Api;
using avalara.comms.rest.v2.Model;
using avalara.comms.rest.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace avalara.comms.rest.v2.Test
{
    /// <summary>
    ///  Class for testing TaxCalculationSettingsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaxCalculationSettingsResponseTests
    {
        // TODO uncomment below to declare an instance variable for TaxCalculationSettingsResponse
        //private TaxCalculationSettingsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaxCalculationSettingsResponse
            //instance = new TaxCalculationSettingsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaxCalculationSettingsResponse
        /// </summary>
        [Test]
        public void TaxCalculationSettingsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TaxCalculationSettingsResponse
            //Assert.IsInstanceOf(typeof(TaxCalculationSettingsResponse), instance);
        }


        /// <summary>
        /// Test the property 'ProfileConfigId'
        /// </summary>
        [Test]
        public void ProfileConfigIdTest()
        {
            // TODO unit test for the property 'ProfileConfigId'
        }
        /// <summary>
        /// Test the property 'ProfileIds'
        /// </summary>
        [Test]
        public void ProfileIdsTest()
        {
            // TODO unit test for the property 'ProfileIds'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'LastUpdateBy'
        /// </summary>
        [Test]
        public void LastUpdateByTest()
        {
            // TODO unit test for the property 'LastUpdateBy'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
        /// <summary>
        /// Test the property 'Exclusions'
        /// </summary>
        [Test]
        public void ExclusionsTest()
        {
            // TODO unit test for the property 'Exclusions'
        }
        /// <summary>
        /// Test the property 'Bundles'
        /// </summary>
        [Test]
        public void BundlesTest()
        {
            // TODO unit test for the property 'Bundles'
        }
        /// <summary>
        /// Test the property 'Nexus'
        /// </summary>
        [Test]
        public void NexusTest()
        {
            // TODO unit test for the property 'Nexus'
        }
        /// <summary>
        /// Test the property 'Overrides'
        /// </summary>
        [Test]
        public void OverridesTest()
        {
            // TODO unit test for the property 'Overrides'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'ItemType'
        /// </summary>
        [Test]
        public void ItemTypeTest()
        {
            // TODO unit test for the property 'ItemType'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Test]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
