# coding: utf-8

"""
    SaasPro

    APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.<br /><br />Effective January 1st, 2022 all Avalara products will be enforcing TLS 1.2 server-side. Please ensure that your implementation sets a minimal of TLS 1.2 encryption when making web requests to Avalara APIs.  # noqa: E501

    The version of the OpenAPI document: v2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from avalara.comms.rest.v2.configuration import Configuration


class GeocodeRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ref': 'str',
        'cass': 'bool',
        'lat': 'float',
        'long': 'float',
        'addr': 'str',
        'city': 'str',
        'st': 'str',
        'zip': 'str'
    }

    attribute_map = {
        'ref': 'ref',
        'cass': 'cass',
        'lat': 'lat',
        'long': 'long',
        'addr': 'addr',
        'city': 'city',
        'st': 'st',
        'zip': 'zip'
    }

    def __init__(self, ref=None, cass=None, lat=None, long=None, addr=None, city=None, st=None, zip=None, local_vars_configuration=None):  # noqa: E501
        """GeocodeRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ref = None
        self._cass = None
        self._lat = None
        self._long = None
        self._addr = None
        self._city = None
        self._st = None
        self._zip = None
        self.discriminator = None

        self.ref = ref
        self.cass = cass
        self.lat = lat
        self.long = long
        self.addr = addr
        self.city = city
        self.st = st
        self.zip = zip

    @property
    def ref(self):
        """Gets the ref of this GeocodeRequest.  # noqa: E501

        Optional reference Id for geocode request.   Only address information or latitude/longitude should be provided in request body but not both.  # noqa: E501

        :return: The ref of this GeocodeRequest.  # noqa: E501
        :rtype: str
        """
        return self._ref

    @ref.setter
    def ref(self, ref):
        """Sets the ref of this GeocodeRequest.

        Optional reference Id for geocode request.   Only address information or latitude/longitude should be provided in request body but not both.  # noqa: E501

        :param ref: The ref of this GeocodeRequest.  # noqa: E501
        :type: str
        """

        self._ref = ref

    @property
    def cass(self):
        """Gets the cass of this GeocodeRequest.  # noqa: E501

        Indicates if the CASS validated address is desired in the results.  # noqa: E501

        :return: The cass of this GeocodeRequest.  # noqa: E501
        :rtype: bool
        """
        return self._cass

    @cass.setter
    def cass(self, cass):
        """Sets the cass of this GeocodeRequest.

        Indicates if the CASS validated address is desired in the results.  # noqa: E501

        :param cass: The cass of this GeocodeRequest.  # noqa: E501
        :type: bool
        """

        self._cass = cass

    @property
    def lat(self):
        """Gets the lat of this GeocodeRequest.  # noqa: E501

        Latitude for geocoding based on lat/long coordinates.  # noqa: E501

        :return: The lat of this GeocodeRequest.  # noqa: E501
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this GeocodeRequest.

        Latitude for geocoding based on lat/long coordinates.  # noqa: E501

        :param lat: The lat of this GeocodeRequest.  # noqa: E501
        :type: float
        """

        self._lat = lat

    @property
    def long(self):
        """Gets the long of this GeocodeRequest.  # noqa: E501

        Longitude for geocoding based on lat/long coordinates.  # noqa: E501

        :return: The long of this GeocodeRequest.  # noqa: E501
        :rtype: float
        """
        return self._long

    @long.setter
    def long(self, long):
        """Sets the long of this GeocodeRequest.

        Longitude for geocoding based on lat/long coordinates.  # noqa: E501

        :param long: The long of this GeocodeRequest.  # noqa: E501
        :type: float
        """

        self._long = long

    @property
    def addr(self):
        """Gets the addr of this GeocodeRequest.  # noqa: E501

        Street address.  # noqa: E501

        :return: The addr of this GeocodeRequest.  # noqa: E501
        :rtype: str
        """
        return self._addr

    @addr.setter
    def addr(self, addr):
        """Sets the addr of this GeocodeRequest.

        Street address.  # noqa: E501

        :param addr: The addr of this GeocodeRequest.  # noqa: E501
        :type: str
        """

        self._addr = addr

    @property
    def city(self):
        """Gets the city of this GeocodeRequest.  # noqa: E501

        City name.  # noqa: E501

        :return: The city of this GeocodeRequest.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this GeocodeRequest.

        City name.  # noqa: E501

        :param city: The city of this GeocodeRequest.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def st(self):
        """Gets the st of this GeocodeRequest.  # noqa: E501

        State name or abbreviation.  # noqa: E501

        :return: The st of this GeocodeRequest.  # noqa: E501
        :rtype: str
        """
        return self._st

    @st.setter
    def st(self, st):
        """Sets the st of this GeocodeRequest.

        State name or abbreviation.  # noqa: E501

        :param st: The st of this GeocodeRequest.  # noqa: E501
        :type: str
        """

        self._st = st

    @property
    def zip(self):
        """Gets the zip of this GeocodeRequest.  # noqa: E501

        Postal code.  # noqa: E501

        :return: The zip of this GeocodeRequest.  # noqa: E501
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """Sets the zip of this GeocodeRequest.

        Postal code.  # noqa: E501

        :param zip: The zip of this GeocodeRequest.  # noqa: E501
        :type: str
        """

        self._zip = zip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeocodeRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GeocodeRequest):
            return True

        return self.to_dict() != other.to_dict()
