<?php
/**
 * TaxCalculationSettingsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SaasPro
 *
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * TaxCalculationSettingsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Data for an invoice or quote line item.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TaxCalculationSettingsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TaxCalculationSettingsResponse"
     */
    public function testTaxCalculationSettingsResponse()
    {
    }

    /**
     * Test attribute "profile_config_id"
     */
    public function testPropertyProfileConfigId()
    {
    }

    /**
     * Test attribute "profile_ids"
     */
    public function testPropertyProfileIds()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "last_update_by"
     */
    public function testPropertyLastUpdateBy()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "settings"
     */
    public function testPropertySettings()
    {
    }

    /**
     * Test attribute "exclusions"
     */
    public function testPropertyExclusions()
    {
    }

    /**
     * Test attribute "bundles"
     */
    public function testPropertyBundles()
    {
    }

    /**
     * Test attribute "nexus"
     */
    public function testPropertyNexus()
    {
    }

    /**
     * Test attribute "overrides"
     */
    public function testPropertyOverrides()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "item_type"
     */
    public function testPropertyItemType()
    {
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
    }

    /**
     * Test attribute "warnings"
     */
    public function testPropertyWarnings()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
