/* 
 * SaasPro
 *
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.
 *
 * The version of the OpenAPI document: v2
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = avalara.comms.rest.v2.Client.OpenAPIDateConverter;

namespace avalara.comms.rest.v2.Model
{
    /// <summary>
    /// LocationItem
    /// </summary>
    [DataContract]
    public partial class LocationItem :  IEquatable<LocationItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocationItem" /> class.
        /// </summary>
        /// <param name="isAlternate">isAlternate.</param>
        /// <param name="countryIso">countryIso.</param>
        /// <param name="state">state.</param>
        /// <param name="county">county.</param>
        /// <param name="locality">locality.</param>
        /// <param name="pCode">pCode.</param>
        public LocationItem(bool isAlternate = default(bool), string countryIso = default(string), string state = default(string), string county = default(string), string locality = default(string), int pCode = default(int))
        {
            this.CountryIso = countryIso;
            this.State = state;
            this.County = county;
            this.Locality = locality;
            this.IsAlternate = isAlternate;
            this.CountryIso = countryIso;
            this.State = state;
            this.County = county;
            this.Locality = locality;
            this.PCode = pCode;
        }
        
        /// <summary>
        /// Gets or Sets IsAlternate
        /// </summary>
        [DataMember(Name="IsAlternate", EmitDefaultValue=false)]
        public bool IsAlternate { get; set; }

        /// <summary>
        /// Gets or Sets CountryIso
        /// </summary>
        [DataMember(Name="CountryIso", EmitDefaultValue=true)]
        public string CountryIso { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name="State", EmitDefaultValue=true)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets County
        /// </summary>
        [DataMember(Name="County", EmitDefaultValue=true)]
        public string County { get; set; }

        /// <summary>
        /// Gets or Sets Locality
        /// </summary>
        [DataMember(Name="Locality", EmitDefaultValue=true)]
        public string Locality { get; set; }

        /// <summary>
        /// Gets or Sets PCode
        /// </summary>
        [DataMember(Name="PCode", EmitDefaultValue=false)]
        public int PCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LocationItem {\n");
            sb.Append("  IsAlternate: ").Append(IsAlternate).Append("\n");
            sb.Append("  CountryIso: ").Append(CountryIso).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  County: ").Append(County).Append("\n");
            sb.Append("  Locality: ").Append(Locality).Append("\n");
            sb.Append("  PCode: ").Append(PCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LocationItem);
        }

        /// <summary>
        /// Returns true if LocationItem instances are equal
        /// </summary>
        /// <param name="input">Instance of LocationItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LocationItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsAlternate == input.IsAlternate ||
                    (this.IsAlternate != null &&
                    this.IsAlternate.Equals(input.IsAlternate))
                ) && 
                (
                    this.CountryIso == input.CountryIso ||
                    (this.CountryIso != null &&
                    this.CountryIso.Equals(input.CountryIso))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.County == input.County ||
                    (this.County != null &&
                    this.County.Equals(input.County))
                ) && 
                (
                    this.Locality == input.Locality ||
                    (this.Locality != null &&
                    this.Locality.Equals(input.Locality))
                ) && 
                (
                    this.PCode == input.PCode ||
                    (this.PCode != null &&
                    this.PCode.Equals(input.PCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsAlternate != null)
                    hashCode = hashCode * 59 + this.IsAlternate.GetHashCode();
                if (this.CountryIso != null)
                    hashCode = hashCode * 59 + this.CountryIso.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.County != null)
                    hashCode = hashCode * 59 + this.County.GetHashCode();
                if (this.Locality != null)
                    hashCode = hashCode * 59 + this.Locality.GetHashCode();
                if (this.PCode != null)
                    hashCode = hashCode * 59 + this.PCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
