/*
 * SaasPro
 *
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.<br /><br />Effective January 1st, 2022 all Avalara products will be enforcing TLS 1.2 server-side. Please ensure that your implementation sets a minimal of TLS 1.2 encryption when making web requests to Avalara APIs.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using avalara.comms.rest.v2.Api;
using avalara.comms.rest.v2.Model;
using avalara.comms.rest.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace avalara.comms.rest.v2.Test.Model
{
    /// <summary>
    ///  Class for testing GeocodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeocodeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeocodeRequest
        //private GeocodeRequest instance;

        public GeocodeRequestTests()
        {
            // TODO uncomment below to create an instance of GeocodeRequest
            //instance = new GeocodeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeocodeRequest
        /// </summary>
        [Fact]
        public void GeocodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeocodeRequest
            //Assert.IsType<GeocodeRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Ref'
        /// </summary>
        [Fact]
        public void RefTest()
        {
            // TODO unit test for the property 'Ref'
        }
        /// <summary>
        /// Test the property 'Cass'
        /// </summary>
        [Fact]
        public void CassTest()
        {
            // TODO unit test for the property 'Cass'
        }
        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Fact]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Long'
        /// </summary>
        [Fact]
        public void LongTest()
        {
            // TODO unit test for the property 'Long'
        }
        /// <summary>
        /// Test the property 'Addr'
        /// </summary>
        [Fact]
        public void AddrTest()
        {
            // TODO unit test for the property 'Addr'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'St'
        /// </summary>
        [Fact]
        public void StTest()
        {
            // TODO unit test for the property 'St'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Fact]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }

    }

}
