/*
 * SaasPro
 *
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.<br /><br />Effective January 1st, 2022 all Avalara products will be enforcing TLS 1.2 server-side. Please ensure that your implementation sets a minimal of TLS 1.2 encryption when making web requests to Avalara APIs.
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using avalara.comms.rest.v2.Api;
using avalara.comms.rest.v2.Model;
using avalara.comms.rest.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace avalara.comms.rest.v2.Test.Model
{
    /// <summary>
    ///  Class for testing LineItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LineItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LineItem
        //private LineItem instance;

        public LineItemTests()
        {
            // TODO uncomment below to create an instance of LineItem
            //instance = new LineItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LineItem
        /// </summary>
        [Fact]
        public void LineItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" LineItem
            //Assert.IsType<LineItem>(instance);
        }


        /// <summary>
        /// Test the property 'Ref'
        /// </summary>
        [Fact]
        public void RefTest()
        {
            // TODO unit test for the property 'Ref'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Chg'
        /// </summary>
        [Fact]
        public void ChgTest()
        {
            // TODO unit test for the property 'Chg'
        }
        /// <summary>
        /// Test the property 'Line'
        /// </summary>
        [Fact]
        public void LineTest()
        {
            // TODO unit test for the property 'Line'
        }
        /// <summary>
        /// Test the property 'Loc'
        /// </summary>
        [Fact]
        public void LocTest()
        {
            // TODO unit test for the property 'Loc'
        }
        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Fact]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }
        /// <summary>
        /// Test the property 'Sale'
        /// </summary>
        [Fact]
        public void SaleTest()
        {
            // TODO unit test for the property 'Sale'
        }
        /// <summary>
        /// Test the property 'Plsp'
        /// </summary>
        [Fact]
        public void PlspTest()
        {
            // TODO unit test for the property 'Plsp'
        }
        /// <summary>
        /// Test the property 'Incl'
        /// </summary>
        [Fact]
        public void InclTest()
        {
            // TODO unit test for the property 'Incl'
        }
        /// <summary>
        /// Test the property 'Pror'
        /// </summary>
        [Fact]
        public void ProrTest()
        {
            // TODO unit test for the property 'Pror'
        }
        /// <summary>
        /// Test the property 'Proadj'
        /// </summary>
        [Fact]
        public void ProadjTest()
        {
            // TODO unit test for the property 'Proadj'
        }
        /// <summary>
        /// Test the property 'Tran'
        /// </summary>
        [Fact]
        public void TranTest()
        {
            // TODO unit test for the property 'Tran'
        }
        /// <summary>
        /// Test the property 'Serv'
        /// </summary>
        [Fact]
        public void ServTest()
        {
            // TODO unit test for the property 'Serv'
        }
        /// <summary>
        /// Test the property 'Dbt'
        /// </summary>
        [Fact]
        public void DbtTest()
        {
            // TODO unit test for the property 'Dbt'
        }
        /// <summary>
        /// Test the property 'Adj'
        /// </summary>
        [Fact]
        public void AdjTest()
        {
            // TODO unit test for the property 'Adj'
        }
        /// <summary>
        /// Test the property 'Adjm'
        /// </summary>
        [Fact]
        public void AdjmTest()
        {
            // TODO unit test for the property 'Adjm'
        }
        /// <summary>
        /// Test the property 'Disc'
        /// </summary>
        [Fact]
        public void DiscTest()
        {
            // TODO unit test for the property 'Disc'
        }
        /// <summary>
        /// Test the property 'Opt'
        /// </summary>
        [Fact]
        public void OptTest()
        {
            // TODO unit test for the property 'Opt'
        }
        /// <summary>
        /// Test the property 'Prop'
        /// </summary>
        [Fact]
        public void PropTest()
        {
            // TODO unit test for the property 'Prop'
        }
        /// <summary>
        /// Test the property 'Bill'
        /// </summary>
        [Fact]
        public void BillTest()
        {
            // TODO unit test for the property 'Bill'
        }
        /// <summary>
        /// Test the property 'Cust'
        /// </summary>
        [Fact]
        public void CustTest()
        {
            // TODO unit test for the property 'Cust'
        }
        /// <summary>
        /// Test the property 'Lfln'
        /// </summary>
        [Fact]
        public void LflnTest()
        {
            // TODO unit test for the property 'Lfln'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }
        /// <summary>
        /// Test the property 'Glref'
        /// </summary>
        [Fact]
        public void GlrefTest()
        {
            // TODO unit test for the property 'Glref'
        }

    }

}
