/**
 * SaasPro
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.<br /><br />Effective January 1st, 2022 all Avalara products will be enforcing TLS 1.2 server-side. Please ensure that your implementation sets a minimal of TLS 1.2 encryption when making web requests to Avalara APIs.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KeyValuePair model module.
 * @module model/KeyValuePair
 * @version v2
 */
class KeyValuePair {
    /**
     * Constructs a new <code>KeyValuePair</code>.
     * Key/value pair data.
     * @alias module:model/KeyValuePair
     */
    constructor() { 
        
        KeyValuePair.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>KeyValuePair</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KeyValuePair} obj Optional instance to populate.
     * @return {module:model/KeyValuePair} The populated <code>KeyValuePair</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KeyValuePair();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('val')) {
                obj['val'] = ApiClient.convertToType(data['val'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Key.
 * @member {String} key
 */
KeyValuePair.prototype['key'] = undefined;

/**
 * Value.
 * @member {String} val
 */
KeyValuePair.prototype['val'] = undefined;






export default KeyValuePair;

