=begin
#SaasPro

#APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CustomizationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomizationApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CustomizationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomizationApi' do
    it 'should create an instance of CustomizationApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CustomizationApi)
    end
  end

  # unit tests for api_v2_profiles_get_profiles_get
  # Retrieves one or more profiles with associated settings and configurable items
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :requested_client_id Client id associated with profile(s) to be fetched  Null value will use client id submitting the request or default client id as applicable.
  # @option opts [Integer] :requested_profile_id Configuration profile id to be fetched  Use 0 to indicate all profiles  Null value will use profile id from request or 0 if not set.
  # @option opts [TaxCalculationSettingTypes] :item_type Item Type  Examples:    Configuration, Bundle, Exclusion, Override, All
  # @return [TaxCalculationSettingsResponse]
  describe 'api_v2_profiles_get_profiles_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v2_profiles_set_bundles_post
  # Creates or updates bundle packages and associated profile mappings.
  # @param [Hash] opts the optional parameters
  # @option opts [SetTaxCalculationSettingRequest] :set_tax_calculation_setting_request 
  # @return [TaxCalculationSettingsResponse]
  describe 'api_v2_profiles_set_bundles_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v2_profiles_set_config_post
  # Creates or updates configuration settings and associated profile mappings.
  # @param [Hash] opts the optional parameters
  # @option opts [SetTaxCalculationSettingRequest] :set_tax_calculation_setting_request 
  # @return [TaxCalculationSettingsResponse]
  describe 'api_v2_profiles_set_config_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v2_profiles_set_exclusions_post
  # Creates or updates exclusions and associated profile mappings.
  # @param [Hash] opts the optional parameters
  # @option opts [SetTaxCalculationSettingRequest] :set_tax_calculation_setting_request 
  # @return [TaxCalculationSettingsResponse]
  describe 'api_v2_profiles_set_exclusions_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v2_profiles_set_overrides_post
  # Creates or updates overrides and associated profile mappings.
  # @param [Hash] opts the optional parameters
  # @option opts [SetTaxCalculationSettingRequest] :set_tax_calculation_setting_request 
  # @return [TaxCalculationSettingsResponse]
  describe 'api_v2_profiles_set_overrides_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
