/*
 * SaasPro
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BundleConfig;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.ExclusionConfig;
import org.openapitools.client.model.ModelConfiguration;
import org.openapitools.client.model.NexusConfig;
import org.openapitools.client.model.OverrideConfig;
import org.openapitools.client.model.Status;
import org.openapitools.client.model.Warning;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TaxCalculationSettingsResponse
 */
public class TaxCalculationSettingsResponseTest {
    private final TaxCalculationSettingsResponse model = new TaxCalculationSettingsResponse();

    /**
     * Model tests for TaxCalculationSettingsResponse
     */
    @Test
    public void testTaxCalculationSettingsResponse() {
        // TODO: test TaxCalculationSettingsResponse
    }

    /**
     * Test the property 'profileConfigId'
     */
    @Test
    public void profileConfigIdTest() {
        // TODO: test profileConfigId
    }

    /**
     * Test the property 'profileIds'
     */
    @Test
    public void profileIdsTest() {
        // TODO: test profileIds
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'lastUpdateBy'
     */
    @Test
    public void lastUpdateByTest() {
        // TODO: test lastUpdateBy
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'exclusions'
     */
    @Test
    public void exclusionsTest() {
        // TODO: test exclusions
    }

    /**
     * Test the property 'bundles'
     */
    @Test
    public void bundlesTest() {
        // TODO: test bundles
    }

    /**
     * Test the property 'nexus'
     */
    @Test
    public void nexusTest() {
        // TODO: test nexus
    }

    /**
     * Test the property 'overrides'
     */
    @Test
    public void overridesTest() {
        // TODO: test overrides
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'itemType'
     */
    @Test
    public void itemTypeTest() {
        // TODO: test itemType
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
