/*
 * SaasPro
 * APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Location data used to determine taxing jurisdiction.
 */
@ApiModel(description = "Location data used to determine taxing jurisdiction.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-05-10T00:57:00.867-04:00[America/New_York]")
public class Location {
  public static final String SERIALIZED_NAME_CNTY = "cnty";
  @SerializedName(SERIALIZED_NAME_CNTY)
  private String cnty;

  public static final String SERIALIZED_NAME_CTRY = "ctry";
  @SerializedName(SERIALIZED_NAME_CTRY)
  private String ctry;

  public static final String SERIALIZED_NAME_INT = "int";
  @SerializedName(SERIALIZED_NAME_INT)
  private Boolean _int;

  public static final String SERIALIZED_NAME_GEO = "geo";
  @SerializedName(SERIALIZED_NAME_GEO)
  private Boolean geo;

  public static final String SERIALIZED_NAME_PCD = "pcd";
  @SerializedName(SERIALIZED_NAME_PCD)
  private Integer pcd;

  public static final String SERIALIZED_NAME_NPA = "npa";
  @SerializedName(SERIALIZED_NAME_NPA)
  private Integer npa;

  public static final String SERIALIZED_NAME_FIPS = "fips";
  @SerializedName(SERIALIZED_NAME_FIPS)
  private String fips;

  public static final String SERIALIZED_NAME_ADDR = "addr";
  @SerializedName(SERIALIZED_NAME_ADDR)
  private String addr;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_ST = "st";
  @SerializedName(SERIALIZED_NAME_ST)
  private String st;

  public static final String SERIALIZED_NAME_ZIP = "zip";
  @SerializedName(SERIALIZED_NAME_ZIP)
  private String zip;


  public Location cnty(String cnty) {
    
    this.cnty = cnty;
    return this;
  }

   /**
   * County name.
   * @return cnty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "County name.")

  public String getCnty() {
    return cnty;
  }


  public void setCnty(String cnty) {
    this.cnty = cnty;
  }


  public Location ctry(String ctry) {
    
    this.ctry = ctry;
    return this;
  }

   /**
   * Country ISO code.
   * @return ctry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Country ISO code.")

  public String getCtry() {
    return ctry;
  }


  public void setCtry(String ctry) {
    this.ctry = ctry;
  }


  public Location _int(Boolean _int) {
    
    this._int = _int;
    return this;
  }

   /**
   * Indicates if the location is within city limits.  Default: true.
   * @return _int
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if the location is within city limits.  Default: true.")

  public Boolean getInt() {
    return _int;
  }


  public void setInt(Boolean _int) {
    this._int = _int;
  }


  public Location geo(Boolean geo) {
    
    this.geo = geo;
    return this;
  }

   /**
   * Indicates if this address should be geocoded in order to obtain taxing jurisdiction.  Default: false.
   * @return geo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if this address should be geocoded in order to obtain taxing jurisdiction.  Default: false.")

  public Boolean getGeo() {
    return geo;
  }


  public void setGeo(Boolean geo) {
    this.geo = geo;
  }


  public Location pcd(Integer pcd) {
    
    this.pcd = pcd;
    return this;
  }

   /**
   * PCode for taxing jurisdiction.
   * @return pcd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PCode for taxing jurisdiction.")

  public Integer getPcd() {
    return pcd;
  }


  public void setPcd(Integer pcd) {
    this.pcd = pcd;
  }


  public Location npa(Integer npa) {
    
    this.npa = npa;
    return this;
  }

   /**
   * NPANXX number.
   * @return npa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "NPANXX number.")

  public Integer getNpa() {
    return npa;
  }


  public void setNpa(Integer npa) {
    this.npa = npa;
  }


  public Location fips(String fips) {
    
    this.fips = fips;
    return this;
  }

   /**
   * FIPS code for taxing jurisdiction.
   * @return fips
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "FIPS code for taxing jurisdiction.")

  public String getFips() {
    return fips;
  }


  public void setFips(String fips) {
    this.fips = fips;
  }


  public Location addr(String addr) {
    
    this.addr = addr;
    return this;
  }

   /**
   * Street address.
   * @return addr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Street address.")

  public String getAddr() {
    return addr;
  }


  public void setAddr(String addr) {
    this.addr = addr;
  }


  public Location city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * City name.
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "City name.")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public Location st(String st) {
    
    this.st = st;
    return this;
  }

   /**
   * State name or abbreviation.
   * @return st
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "State name or abbreviation.")

  public String getSt() {
    return st;
  }


  public void setSt(String st) {
    this.st = st;
  }


  public Location zip(String zip) {
    
    this.zip = zip;
    return this;
  }

   /**
   * Postal code.
   * @return zip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Postal code.")

  public String getZip() {
    return zip;
  }


  public void setZip(String zip) {
    this.zip = zip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Location location = (Location) o;
    return Objects.equals(this.cnty, location.cnty) &&
        Objects.equals(this.ctry, location.ctry) &&
        Objects.equals(this._int, location._int) &&
        Objects.equals(this.geo, location.geo) &&
        Objects.equals(this.pcd, location.pcd) &&
        Objects.equals(this.npa, location.npa) &&
        Objects.equals(this.fips, location.fips) &&
        Objects.equals(this.addr, location.addr) &&
        Objects.equals(this.city, location.city) &&
        Objects.equals(this.st, location.st) &&
        Objects.equals(this.zip, location.zip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cnty, ctry, _int, geo, pcd, npa, fips, addr, city, st, zip);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Location {\n");
    sb.append("    cnty: ").append(toIndentedString(cnty)).append("\n");
    sb.append("    ctry: ").append(toIndentedString(ctry)).append("\n");
    sb.append("    _int: ").append(toIndentedString(_int)).append("\n");
    sb.append("    geo: ").append(toIndentedString(geo)).append("\n");
    sb.append("    pcd: ").append(toIndentedString(pcd)).append("\n");
    sb.append("    npa: ").append(toIndentedString(npa)).append("\n");
    sb.append("    fips: ").append(toIndentedString(fips)).append("\n");
    sb.append("    addr: ").append(toIndentedString(addr)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    st: ").append(toIndentedString(st)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

