=begin comment

SaasPro

APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::SetTaxCalculationSettingRequest;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use WWW::OpenAPIClient::Object::BundleConfig;
use WWW::OpenAPIClient::Object::Configuration;
use WWW::OpenAPIClient::Object::ExclusionConfig;
use WWW::OpenAPIClient::Object::NexusConfig;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#Data for an invoice or quote line item.
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

SaasPro

APIs to interface with communications tax engine.<br />The API requires Basic authentication.<br />Users with access to multiple clients must also set request header parameter for <code>client_id</code>.<br />Set <code>client_profile_id</code> to specify profile to be used for taxation.

The version of the OpenAPI document: v2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new { 
    my ($class, %args) = @_; 

    my $self = bless {}, $class;

    $self->init(%args);
    
    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }

    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'Data for an invoice or quote line item.',
                                  class => 'SetTaxCalculationSettingRequest',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'profile_config_id' => {
        datatype => 'int',
        base_name => 'ProfileConfigId',
        description => 'Profile configuration id to be used when updating an existing profile  Use null for new configuration',
        format => '',
        read_only => '',
            },
    'link_profile_ids' => {
        datatype => 'ARRAY[int]',
        base_name => 'LinkProfileIds',
        description => 'Profile(s) to be added to configuration  Leave null to not change profiles associated with configuration settings',
        format => '',
        read_only => '',
            },
    'unlink_profile_ids' => {
        datatype => 'ARRAY[int]',
        base_name => 'UnlinkProfileIds',
        description => 'Profile(s) to be added to configuration  Leave null to not change profiles associated with configuration settings',
        format => '',
        read_only => '',
            },
    'client_id' => {
        datatype => 'int',
        base_name => 'ClientId',
        description => 'Client id associated with profile(s) to be fetched  Null value will use client id submitting the request or default client id as applicable',
        format => '',
        read_only => '',
            },
    'deactivate' => {
        datatype => 'boolean',
        base_name => 'Deactivate',
        description => 'True &#x3D; Deactivate the configuration  Requires ProfileConfigId to be provided and valid.  Automatically removes any profile mappings associated with the configuration.',
        format => '',
        read_only => '',
            },
    'description' => {
        datatype => 'string',
        base_name => 'Description',
        description => 'Description to be applied to requested configuration',
        format => '',
        read_only => '',
            },
    'replace_existing_links' => {
        datatype => 'boolean',
        base_name => 'ReplaceExistingLinks',
        description => 'Flag indicating existing configuration links to profile should be replaced  This only applies when one or more profiles have been specified to be linked.   - If true, mapping conflicts will be resolved by removing other links.   - If false, mapping conflicts will cause the request to fail with an error returned.',
        format => '',
        read_only => '',
            },
    'settings' => {
        datatype => 'Configuration',
        base_name => 'Settings',
        description => 'Configuration settings (required)',
        format => '',
        read_only => '',
            },
    'exclusions' => {
        datatype => 'ARRAY[ExclusionConfig]',
        base_name => 'Exclusions',
        description => 'List of exclusions',
        format => '',
        read_only => '',
            },
    'bundles' => {
        datatype => 'ARRAY[BundleConfig]',
        base_name => 'Bundles',
        description => 'List of bundles',
        format => '',
        read_only => '',
            },
    'nexus' => {
        datatype => 'ARRAY[NexusConfig]',
        base_name => 'Nexus',
        description => 'List of nexus',
        format => '',
        read_only => '',
            },
    'overrides' => {
        datatype => 'ARRAY[string]',
        base_name => 'Overrides',
        description => 'Overrides',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'profile_config_id' => 'int',
    'link_profile_ids' => 'ARRAY[int]',
    'unlink_profile_ids' => 'ARRAY[int]',
    'client_id' => 'int',
    'deactivate' => 'boolean',
    'description' => 'string',
    'replace_existing_links' => 'boolean',
    'settings' => 'Configuration',
    'exclusions' => 'ARRAY[ExclusionConfig]',
    'bundles' => 'ARRAY[BundleConfig]',
    'nexus' => 'ARRAY[NexusConfig]',
    'overrides' => 'ARRAY[string]'
} );

__PACKAGE__->attribute_map( {
    'profile_config_id' => 'ProfileConfigId',
    'link_profile_ids' => 'LinkProfileIds',
    'unlink_profile_ids' => 'UnlinkProfileIds',
    'client_id' => 'ClientId',
    'deactivate' => 'Deactivate',
    'description' => 'Description',
    'replace_existing_links' => 'ReplaceExistingLinks',
    'settings' => 'Settings',
    'exclusions' => 'Exclusions',
    'bundles' => 'Bundles',
    'nexus' => 'Nexus',
    'overrides' => 'Overrides'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
